[project]
name = "drex"
version = "0.1.0"
description = "Assembler 0 - Open Source Low Cost Assembly Robot"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Jack Vial", email = "vialjack@gmail.com"}
]
dependencies = [
    "click>=8.0",
    "rich>=13.0",
    "rerun-sdk==0.22.0",
]

[project.scripts]
drex = "drex.cli:main"

# Workspace dependencies inherited from root
# assembler0-agents and assembler0-training sources defined in root pyproject.toml

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/drex"]